version: '3.3'
services:
  db:
    image: mysql:5.7.11
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  app:
    image: php-mysql
    ports:
      - 9191:80
    volumes:
      - ./codeigniter:/var/www/html/
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_SERVER: db
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4444:80
  sass:
    image: larryprice/sass
    volumes:
      - ./codeigniter/css:/src
volumes:
  mysql:
